"""Export the SQLite graph as the plain-text shard format in .claude/prompts/graph-schema.md.

This keeps the LLM agents (bug-tracer, impact-analyst, ...) working from the same files whether the graph
was built by this engine or by the graph-indexer agent.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date

from .config import Paths
from .store import Store


def _f(value: object) -> str:
    return str(value if value is not None else "").replace("|", "¦").replace("\n", " ").replace("\r", " ")


def slug(relpath: str) -> str:
    return relpath.replace("/", "__") + ".graph.md"


def _write_if_changed(path, text: str) -> None:
    try:
        if path.read_text(encoding="utf-8") == text:
            return
    except OSError:
        pass
    path.write_text(text, encoding="utf-8")


def export(store: Store, paths: Paths) -> None:
    paths.shards.mkdir(parents=True, exist_ok=True)
    db = store.db
    files = list(db.execute("SELECT * FROM files ORDER BY path"))
    by_file_syms = defaultdict(list)
    for r in db.execute("SELECT * FROM symbols ORDER BY file, start, id"):
        by_file_syms[r["file"]].append(r)
    by_file_edges = defaultdict(list)
    for r in db.execute("SELECT * FROM edges ORDER BY file, line, type, src, dst"):
        by_file_edges[r["file"]].append(r)

    live = set()
    for row in files:
        name = slug(row["path"])
        live.add(name)
        lines = [f"# shard for {row['path']} (generated by codeatlas; do not edit)"]
        if row["error"]:
            lines.append(f"# parse-error: {_f(row['error'])}")
        lines.append(f"FILE|{_f(row['path'])}|{row['lang']}|{row['sha']}|{row['line_count']}")
        for s in by_file_syms[row["path"]]:
            lines.append(f"SYM|{_f(s['id'])}|{s['kind']}|{s['start']}-{s['end']}|{_f(s['signature'])}|{_f(s['summary'])}")
        for e in by_file_edges[row["path"]]:
            lines.append(f"EDGE|{e['type']}|{_f(e['src'])}|{_f(e['dst'])}|{e['line']}|{e['conf']}")
        _write_if_changed(paths.shards / name, "\n".join(lines) + "\n")
    for old in paths.shards.glob("*.graph.md"):
        if old.name not in live:
            old.unlink()

    meta = store.meta()
    manifest = ["# manifest — one line per indexed file: <relpath>|<sha12>|<indexed-at>|<status>",
                "# owner: codeatlas engine"]
    manifest += [f"{_f(r['path'])}|{r['sha']}|{(r['indexed_at'] or '')[:10]}|linked" for r in files]
    _write_if_changed(paths.graph / "manifest.md", "\n".join(manifest) + "\n")

    keys = ["schemaVersion", "lastFullIndex", "lastLink", "lastCluster", "fileCount", "symbolCount", "edgeCount",
            "unresolvedCount", "languages", "clusterAlgo"]
    _write_if_changed(paths.graph / "meta.md",
                      "# meta — graph statistics (generated by codeatlas)\n" + "".join(f"{k}: {meta.get(k, 'never')}\n" for k in keys))

    lines = ["# unresolved — UNRES|<src-id>|<name>|<line>|<candidates or none>|<reason>", "# owner: codeatlas engine"]
    lines += [f"UNRES|{_f(r['src'])}|{_f(r['name'])}|{r['line']}|{_f(r['candidates']) or 'none'}|{r['reason']}"
              for r in db.execute("SELECT * FROM unresolved ORDER BY file, line, name")]
    _write_if_changed(paths.graph / "unresolved.md", "\n".join(lines) + "\n")

    lines = [f"# clusters — generated by codeatlas ({meta.get('clusterAlgo', '?')}) on {date.today().isoformat()}; approximate"]
    for c in db.execute("SELECT * FROM clusters ORDER BY CAST(SUBSTR(id, 2) AS INTEGER)"):
        lines.append(f"CLUSTER|{c['id']}|{_f(c['label'])}|{c['size']}|{c['cohesion']}|{_f(c['summary'])}")
        lines += [f"MEMBER|{c['id']}|{_f(m['symbol_id'])}"
                  for m in db.execute("SELECT symbol_id FROM cluster_members WHERE cluster_id=? ORDER BY symbol_id", (c["id"],))]
    _write_if_changed(paths.graph / "clusters.md", "\n".join(lines) + "\n")

    lines = [f"# processes — generated by codeatlas on {date.today().isoformat()}"]
    for p in db.execute("SELECT * FROM processes ORDER BY CAST(SUBSTR(id, 2) AS INTEGER)"):
        lines.append(f"PROCESS|{p['id']}|{_f(p['name'])}|{_f(p['entry'])}|{p['steps']}|{_f(p['summary'])}")
        lines += [f"STEP|{p['id']}|{s['ord']}|{_f(s['symbol_id'])}"
                  for s in db.execute("SELECT ord, symbol_id FROM process_steps WHERE process_id=? ORDER BY ord", (p["id"],))]
    _write_if_changed(paths.graph / "processes.md", "\n".join(lines) + "\n")
